version: "3.5"

networks:
  proxy:
    external: true
  default:
    driver: bridge

services:
  web:
    image: nginx:latest
    container_name: bootsapmles_web
    labels:
      - "${DOCKER_HOST_FRONTEND}"
      - "traefik.docker.network=proxy"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
      - default
    depends_on:
      - php

  php:
    build:
      context: docker/php
    container_name: bootsamples_php
    volumes:
      - .:/var/www/html:cached
    expose:
      - 9001
    ports:
      - "9000:9000"
    environment:
      - PHP_XDEBUG_ENABLED=${PHP_XDEBUG_ENABLED}
      - APP_ENV=${APP_ENV}