# Home
list:
  path: /
  controller: App\Controller\ListController::index

# Templates
templates.photo.gallery:
  path: /templates/photo-galery
  controller: App\Controller\TemplatesController::photoGallery

templates.video.gallery:
  path: /templates/video-galery
  controller: App\Controller\TemplatesController::videoGallery

templates.mixed.gallery:
  path: /templates/mixed-galery
  controller: App\Controller\TemplatesController::mixedGallery

templates.login:
  path: /templates/login
  controller: App\Controller\TemplatesController::login

templates.contact:
  path: /templates/contact
  controller: App\Controller\TemplatesController::contact

templates.footer:
  path: /templates/footer
  controller: App\Controller\TemplatesController::footer

templates.sitemap:
  path: /templates/sitemap
  controller: App\Controller\TemplatesController::sitemap

templates.shortcuts:
  path: /templates/shortcuts
  controller: App\Controller\TemplatesController::shortcuts

templates.faq:
  path: /templates/faq
  controller: App\Controller\TemplatesController::faq

templates.thanks:
  path: /templates/thanks
  controller: App\Controller\TemplatesController::thanks

templates.employees:
  path: /templates/employees
  controller: App\Controller\TemplatesController::employees

templates.pricing:
  path: /templates/pricing
  controller: App\Controller\TemplatesController::pricing

templates.create.account:
  path: /templates/create-account
  controller: App\Controller\TemplatesController::createAccount

# Page Blog
pages.blog.index:
  path: /blog
  controller: App\Controller\BlogController::index

pages.blog.post.grid:
  path: /blog/post/grid
  controller: App\Controller\BlogController::postGrid

pages.blog.post.audio:
  path: /blog/post/audio
  controller: App\Controller\BlogController::postAudio

pages.blog.post.gallery:
  path: /blog/post/gallery
  controller: App\Controller\BlogController::postGallery

pages.blog.post.text:
  path: /blog/post/text
  controller: App\Controller\BlogController::postText

pages.blog.post.video:
  path: /blog/post/video
  controller: App\Controller\BlogController::postVideo

# Page Business
pages.business.index:
  path: /business
  controller: App\Controller\BusinessController::index

pages.business.services:
  path: /business/services
  controller: App\Controller\BusinessController::services

pages.business.about:
  path: /business/about
  controller: App\Controller\BusinessController::about

pages.business.team:
  path: /business/team
  controller: App\Controller\BusinessController::team

pages.business.contact:
  path: /business/contact
  controller: App\Controller\BusinessController::contact

# Faq page
pages.faq.index:
  path: /faq
  controller: App\Controller\FaqController::index

pages.faq.article:
  path: /faq/article
  controller: App\Controller\FaqController::article

pages.faq.category:
  path: /faq/category
  controller: App\Controller\FaqController::category

# Forum page
pages.forum.index:
  path: /forum
  controller: App\Controller\ForumController::index

pages.forum.topic.new:
  path: /forum/topic/new
  controller: App\Controller\ForumController::newTopic

pages.forum.overview.category:
  path: /forum/category/overview
  controller: App\Controller\ForumController::categoryOverview

pages.forum.topic.overview:
  path: /forum/topic/overview
  controller: App\Controller\ForumController::topicOverview

pages.forum.topic.post:
  path: /forum/topic/post
  controller: App\Controller\ForumController::Post

# Landing page
pages.landing.index:
  path: /landing
  controller: App\Controller\LandingController::index

# Resume page
pages.resume.index:
  path: /resume
  controller: App\Controller\ResumeController::index

# Survey page
pages.survey.index:
  path: /survey
  controller: App\Controller\SurveyController::index

# Admin panel page
pages.admin.index:
  path: /admin
  controller: App\Controller\LandingController::index
